shijieyijiname: 世界一级方程式大奖赛  formula one grand prix
url: https://zhaohandong.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: leader
    name: 领队 leader
  - key: 1
    name: 车手 driver
  - key: 2
    name: 车手 driver
  - key: 2
    name: 车手 driver


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: dzh Home
    link: /
  - title: 科研项目 Research
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
