name: 世界一级方程式大奖赛  formula one grand prix
url: https://zhaohandong.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: leader
    name: 领队 leader
  - key: 1
    name: 本人 self
  - key: 2
    name: 队友 team member
  - key: 2
    name: 车队 convoys


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 奖项 award
    link: /research.html
  - title: 荣誉 reputation
    link: /publications.html
